### ISSUE TITLE
Confirmation email gets blocked by spam filter

### ISSUE THREAD

**Issue by drmercer** [cryptoapp-cs428/cryptoapp-cs428#4]
Inbox by Gmail blocks the confirmation email... might be worth trying to address

**Comment by joshuakcockrell** [comment]
I just changed some stuff in the email text. That bumped our anti-spam rating from 6.4/10 to 8.5/10.

[You can view our current rating here](https://www.mail-tester.com/web-z8ags)

Looks like we are still getting docked points because we are sending the emails from heroku, and the heroku ip's seem to be on a couple blacklists. Not much we can do about that.

**Comment by drmercer** [comment]
Oh hmm. Yeah I'll give it another go

**Comment by drmercer** [comment]
Ayyyyy it worked! Nice job :+1:
